# Generated by Django 4.2.7 on 2023-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Infra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("load_name", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridge", "橋梁"),
                            ("pedestrian", "歩道橋"),
                            ("other", "その他"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
