# Generated by Django 4.2.7 on 2024-02-29 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="title",
            new_name="案件名",
        ),
    ]
