# Generated by Django 4.2.7 on 2024-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panorama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="panoramas/")),
                ("checked", models.BooleanField(default=False)),
            ],
        ),
    ]
