# Generated by Django 4.2.7 on 2024-02-29 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="橋梁名",
            new_name="title",
        ),
    ]
