# Generated by Django 4.2.7 on 2023-11-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="full_width",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infra",
            name="length",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infra",
            name="span_number",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
