# Generated by Django 4.2.7 on 2024-02-14 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="category",
            new_name="カテゴリー",
        ),
    ]
