# Generated by Django 4.2.7 on 2024-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_rename_橋梁名_infra_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Damage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
