# Generated by Django 4.2.7 on 2024-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_panorama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panorama",
            name="image",
            field=models.ImageField(upload_to="panorama/"),
        ),
    ]
