# Generated by Django 4.2.7 on 2024-02-19 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_rename_category_article_カテゴリー"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
            ),
            preserve_default=False,
        ),
    ]
