# Generated by Django 4.2.7 on 2023-11-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0002_infra_full_width_infra_length_infra_span_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="full_width",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="infra",
            name="length",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="infra",
            name="span_number",
            field=models.IntegerField(),
        ),
    ]
