# Generated by Django 4.2.7 on 2024-02-25 05:05

from django.db import migrations, models
import infra.views


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0003_infra_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to=infra.views.upload_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name="Uploads",
            fields=[
                ("primary_key", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
