# Generated by Django 4.2.7 on 2023-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0003_alter_infra_full_width_alter_infra_length_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("article_name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("other", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bridge", "橋梁"),
                            ("pedestrian", "歩道橋"),
                            ("other", "その他"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
