# Generated by Django 4.2.7 on 2024-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0003_alter_panorama_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("single_number", models.CharField(max_length=5)),
                ("double_number_one", models.CharField(max_length=5)),
                ("double_number_two", models.CharField(max_length=5)),
            ],
        ),
    ]
