# Generated by Django 4.2.7 on 2024-04-01 05:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0004_item_selection"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Number",
        ),
        migrations.RemoveField(
            model_name="selection",
            name="item",
        ),
        migrations.RemoveField(
            model_name="selection",
            name="user",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Selection",
        ),
    ]
