# Generated by Django 4.2.7 on 2024-04-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0005_delete_number_remove_selection_item_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Number",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("syuketa", "主桁"),
                            ("yokoketa", "横桁"),
                            ("PCteityakubu", "PC定着部"),
                        ],
                        max_length=100,
                    ),
                ),
                ("top_number", models.CharField(max_length=5)),
                ("bottom_number", models.CharField(max_length=5)),
                ("single_number", models.CharField(max_length=5)),
            ],
        ),
    ]
