# Generated by Django 4.2.7 on 2023-12-13 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0005_infra_top_structure"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="top_structure",
            new_name="top_structure1",
        ),
    ]
