# Generated by Django 4.2.7 on 2023-12-13 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0006_rename_top_structure_infra_top_structure1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="top_structure1",
            new_name="top_structure",
        ),
    ]
