# Generated by Django 4.2.7 on 2024-04-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0006_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="number",
            name="bottom_number",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="number",
            name="single_number",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="number",
            name="top_number",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
