# Generated by Django 4.2.7 on 2023-12-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0007_rename_top_structure1_infra_top_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="bottom_structure",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
