# Generated by Django 4.2.7 on 2023-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0008_infra_bottom_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="manager",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
