# Generated by Django 4.2.7 on 2024-04-15 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0009_remove_image_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamagePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("document", models.FileField(upload_to="photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
