# Generated by Django 4.2.7 on 2023-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0009_article_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
            ],
        ),
    ]
