# Generated by Django 4.2.7 on 2024-04-15 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0010_damagepicture"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DamagePicture",
        ),
    ]
