# Generated by Django 4.2.7 on 2023-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0010_uploadedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="files",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="uploads/",
                verbose_name="Files",
            ),
        ),
        migrations.CreateModel(
            name="MultiUploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("files", models.ManyToManyField(to="infra.uploadedfile")),
            ],
        ),
    ]
