# Generated by Django 4.2.7 on 2024-04-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0011_delete_damagepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="交通量",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="infra",
            name="大型車混入率",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
