# Generated by Django 4.2.7 on 2023-12-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0011_remove_uploadedfile_file_uploadedfile_files_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
            ],
        ),
    ]
