# Generated by Django 4.2.7 on 2024-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0012_infra_交通量_infra_大型車混入率"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=100)),
                ("second", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "交通規制",
                    models.CharField(
                        choices=[
                            ("one", "無し"),
                            ("two", "片側交互通行"),
                            ("three", "車線減少"),
                            ("four", "歩道規制"),
                            ("unknown", "通行止め"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="infra",
            name="交通規制",
        ),
        migrations.AddField(
            model_name="infra",
            name="交通規制",
            field=models.ManyToManyField(to="infra.regulation"),
        ),
    ]
