# Generated by Django 4.2.7 on 2023-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0012_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="files",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(default=1, upload_to="uploads/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MultiUploadedFile",
        ),
    ]
