# Generated by Django 4.2.7 on 2023-12-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0013_remove_uploadedfile_files_uploadedfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
