# Generated by Django 4.2.7 on 2024-05-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0014_approach_loadgrade_loadweight_rulebook_thirdparty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_location", models.CharField(max_length=100)),
                ("damage_type", models.CharField(max_length=100)),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="infra.infra"
                    ),
                ),
            ],
        ),
    ]
