# Generated by Django 4.2.7 on 2024-01-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0015_remove_infra_latitude_remove_infra_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="latitude",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="infra",
            name="longitude",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
