# Generated by Django 4.2.7 on 2024-06-01 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0015_tableview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TableView",
            new_name="Table",
        ),
        migrations.DeleteModel(
            name="Upload",
        ),
    ]
