# Generated by Django 4.2.7 on 2024-06-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0016_rename_tableview_table_delete_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="dxf",
            field=models.FileField(
                default="default_value",
                upload_to="infra/table/dxf/",
                verbose_name="dxfファイル",
            ),
            preserve_default=False,
        ),
    ]
