# Generated by Django 4.2.7 on 2024-06-05 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0017_table_dxf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="damage_type",
        ),
    ]
