# Generated by Django 4.2.7 on 2024-01-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0018_infra_load_grade_alter_infra_live_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="infra",
            name="rule_book",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
