# Generated by Django 4.2.7 on 2024-06-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0018_remove_table_damage_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="damage_location",
        ),
        migrations.AlterField(
            model_name="table",
            name="infra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.infra",
                verbose_name="橋梁名",
            ),
        ),
    ]
