# Generated by Django 4.2.7 on 2024-06-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0019_remove_table_damage_location_alter_table_infra"),
    ]

    operations = [
        migrations.CreateModel(
            name="NameEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("alphabet", models.CharField(max_length=50)),
            ],
        ),
    ]
