# Generated by Django 4.2.7 on 2024-01-05 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0020_infra_coastline_distance_infra_notices_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="length",
            new_name="橋長",
        ),
    ]
