# Generated by Django 4.2.7 on 2024-06-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0020_nameentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=100)),
                ("number", models.CharField(max_length=50)),
            ],
        ),
    ]
