# Generated by Django 4.2.7 on 2024-06-29 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0021_partsnumber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Number",
        ),
    ]
