# Generated by Django 4.2.7 on 2024-01-05 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0022_rename_full_width_infra_全幅員_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="category",
            new_name="カテゴリー",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="bottom_structure",
            new_name="上部構造形式",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="coastline_distance",
            new_name="下部構造形式",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="notices",
            new_name="交通規制",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="proximity_method",
            new_name="基礎構造形式",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="code",
            new_name="橋梁コード",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="live_load",
            new_name="活荷重",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="road_conditions",
            new_name="海岸線との距離",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="third_party",
            new_name="特記事項",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="top_structure",
            new_name="第三者点検の有無",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="load_grade",
            new_name="等級",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="latitude",
            new_name="経度",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="load_name",
            new_name="緯度",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="traffic_regulation",
            new_name="路下条件",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="longitude",
            new_name="路線名",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="under_structure",
            new_name="近接方法",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="rule_book",
            new_name="適用示方書",
        ),
    ]
