# Generated by Django 4.2.7 on 2024-01-05 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0023_rename_category_infra_カテゴリー_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="経度",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="緯度",
            new_name="longitude",
        ),
    ]
