# Generated by Django 4.2.7 on 2024-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0023_main_frame_material_partsnumber_main_frame_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsnumber",
            name="symbol",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
