# Generated by Django 4.2.7 on 2024-01-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0024_rename_経度_infra_latitude_rename_緯度_infra_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="特記事項",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
