# Generated by Django 4.2.7 on 2024-01-06 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0025_alter_infra_特記事項"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="latitude",
            new_name="経度",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="longitude",
            new_name="緯度",
        ),
    ]
