# Generated by Django 4.2.7 on 2024-01-06 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0026_rename_latitude_infra_経度_rename_longitude_infra_緯度"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infra",
            old_name="経度",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="infra",
            old_name="緯度",
            new_name="longitude",
        ),
    ]
