# Generated by Django 4.2.7 on 2024-07-06 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0027_alter_partsnumber_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partsnumber",
            name="main_frame",
        ),
        migrations.RemoveField(
            model_name="partsnumber",
            name="material",
        ),
        migrations.DeleteModel(
            name="Main_frame",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
