# Generated by Django 4.2.7 on 2024-01-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0027_rename_経度_infra_latitude_rename_緯度_infra_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="全幅員",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="infra",
            name="橋長",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
