# Generated by Django 4.2.7 on 2024-07-07 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0028_remove_partsnumber_main_frame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameentry",
            name="alphabet",
            field=models.CharField(
                max_length=50,
                validators=[django.core.validators.RegexValidator(regex="[A-Za-z]+")],
            ),
        ),
    ]
