# Generated by Django 4.2.7 on 2024-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0028_alter_infra_全幅員_alter_infra_橋長"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infra",
            name="latitude",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="infra",
            name="longitude",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
