# Generated by Django 4.2.7 on 2024-07-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0029_alter_nameentry_alphabet"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameentry",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.article",
            ),
        ),
    ]
