# Generated by Django 4.2.7 on 2024-07-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0030_nameentry_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("材料", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="main_frame",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="material",
            field=models.ManyToManyField(to="infra.material"),
        ),
    ]
