# Generated by Django 4.2.7 on 2024-01-30 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0030_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
    ]
