# Generated by Django 4.2.7 on 2024-01-30 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0031_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
