# Generated by Django 4.2.7 on 2024-07-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0032_main_frame_remove_partsnumber_main_frame_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partsnumber",
            name="main_frame",
        ),
        migrations.DeleteModel(
            name="Main_Frame",
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="main_frame",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
