# Generated by Django 4.2.7 on 2024-07-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0033_remove_partsnumber_main_frame_delete_main_frame_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("部材名", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="partsnumber",
            name="parts_name",
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="parts_name",
            field=models.ManyToManyField(to="infra.partsname"),
        ),
    ]
