# Generated by Django 4.2.7 on 2024-07-13 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0034_partsname_remove_partsnumber_parts_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsname",
            name="material",
            field=models.ManyToManyField(to="infra.material"),
        ),
        migrations.RemoveField(
            model_name="partsnumber",
            name="parts_name",
        ),
        migrations.AddField(
            model_name="partsnumber",
            name="parts_name",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.partsname",
                verbose_name="部材名",
            ),
            preserve_default=False,
        ),
    ]
