# Generated by Django 4.2.7 on 2024-07-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0035_partsname_material_remove_partsnumber_parts_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsname",
            name="記号",
            field=models.CharField(default="Sx", max_length=50),
            preserve_default=False,
        ),
    ]
