# Generated by Django 4.2.7 on 2024-07-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0036_partsname_記号"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsname",
            name="main_frame",
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
