# Generated by Django 4.2.7 on 2024-07-14 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0037_partsname_main_frame"),
    ]

    operations = [
        migrations.RenameField(
            model_name="partsname",
            old_name="main_frame",
            new_name="主要部材",
        ),
    ]
