# Generated by Django 4.2.7 on 2024-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0038_rename_main_frame_partsname_主要部材"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=255)),
                ("damage_name", models.CharField(max_length=255)),
                ("join", models.CharField(max_length=255)),
                ("picture_number", models.CharField(max_length=255)),
                ("this_time_picture", models.CharField(max_length=255)),
                ("last_time_picture", models.CharField(max_length=255)),
                ("textarea_content", models.CharField(max_length=255)),
                ("damage_coordinate", models.CharField(max_length=255)),
                ("picture_coordinate", models.CharField(max_length=255)),
            ],
        ),
    ]
