# Generated by Django 4.2.7 on 2024-07-23 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0039_fullreportdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsnumber",
            name="infra",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.infra",
                verbose_name="Infra",
            ),
            preserve_default=False,
        ),
    ]
