# Generated by Django 4.2.7 on 2024-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0042_remove_fullreportdata_damage_coordinate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="special_links",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
