# Generated by Django 4.2.7 on 2024-07-26 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0044_fullreportdata_part_split"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fullreportdata",
            old_name="part_split",
            new_name="parts_split",
        ),
    ]
