# Generated by Django 4.2.7 on 2024-07-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0045_rename_part_split_fullreportdata_parts_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullreportdata",
            name="infra",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.infra",
                verbose_name="Infra",
            ),
            preserve_default=False,
        ),
    ]
