# Generated by Django 4.2.7 on 2024-07-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0046_fullreportdata_infra"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagecomment",
            name="cause",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="comment",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="damage_lank",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="damage_name",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="jadgement",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="main_parts",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="parts_name",
            field=models.CharField(default=14, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="special_links",
            field=models.ForeignKey(
                default=14,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.fullreportdata",
                verbose_name="special_links",
            ),
            preserve_default=False,
        ),
    ]
