# Generated by Django 4.2.7 on 2024-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0049_remove_fullreportdata_unique_parts_damage_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fullreportdata",
            name="unique_parts_damage",
        ),
        migrations.AddConstraint(
            model_name="fullreportdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "damage_name",
                    "parts_split",
                    "join",
                    "damage_coordinate_x",
                    "damage_coordinate_y",
                    "span_number",
                    "special_links",
                ),
                name="unique_parts_damage",
            ),
        ),
    ]
