# Generated by Django 4.2.7 on 2024-07-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0050_remove_fullreportdata_unique_parts_damage_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fullreportdata",
            name="unique_parts_damage",
        ),
        migrations.AlterField(
            model_name="fullreportdata",
            name="last_time_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fullreportdata",
            name="picture_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fullreportdata",
            name="this_time_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="fullreportdata",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "damage_name",
                    "parts_split",
                    "join",
                    "span_number",
                    "special_links",
                ),
                name="unique_parts_damage",
            ),
        ),
    ]
