# Generated by Django 4.2.7 on 2024-07-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0052_remove_fullreportdata_unique_parts_damage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partsnumber",
            name="span_number",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DamageList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parts_name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("material", models.CharField(max_length=255)),
                ("main_parts", models.CharField(max_length=255)),
                ("damage_name", models.CharField(max_length=255)),
                ("damage_max_lank", models.CharField(max_length=255)),
                ("damage_min_lank", models.CharField(max_length=255)),
                ("Classification", models.CharField(max_length=255)),
                ("pattern", models.CharField(max_length=255)),
                ("span_number", models.CharField(max_length=255)),
                (
                    "infra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infra.infra",
                        verbose_name="Infra",
                    ),
                ),
            ],
        ),
    ]
