# Generated by Django 4.2.7 on 2024-07-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0053_partsnumber_span_number_damagelist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="damagelist",
            name="Classification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="damagelist",
            name="damage_max_lank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="damagelist",
            name="damage_min_lank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="damagelist",
            name="pattern",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="damagelist",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "symbol",
                    "number",
                    "material",
                    "main_parts",
                    "damage_name",
                    "span_number",
                    "infra",
                ),
                name="unique_damage_list",
            ),
        ),
    ]
