# Generated by Django 4.2.7 on 2024-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0055_rename_classification_damagelist_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="fullreportdata",
            name="classification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="damage_size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="damage_unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="measurement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fullreportdata",
            name="pattern",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
