# Generated by Django 4.2.7 on 2024-07-31 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0056_fullreportdata_classification_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damagecomment",
            old_name="damage_lank",
            new_name="material",
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="damage_max_lank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="damage_min_lank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="infra",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="infra.infra",
                verbose_name="Infra",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="span_number",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="damagecomment",
            name="cause",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="damagecomment",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="damagecomment",
            name="jadgement",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="damagecomment",
            constraint=models.UniqueConstraint(
                fields=(
                    "parts_name",
                    "main_parts",
                    "damage_name",
                    "span_number",
                    "infra",
                ),
                name="unique_damage_comment",
            ),
        ),
    ]
