# Generated by Django 4.2.7 on 2024-07-31 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0057_rename_damage_lank_damagecomment_material_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="damagecomment",
            name="special_links",
        ),
    ]
