# Generated by Django 4.2.7 on 2024-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0058_remove_damagecomment_special_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damagecomment",
            old_name="picture",
            new_name="this_time_picture",
        ),
    ]
