# Generated by Django 4.2.7 on 2024-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0059_rename_picture_damagecomment_this_time_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="damagecomment",
            name="this_time_picture",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
