# Generated by Django 4.2.7 on 2024-08-01 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0060_alter_damagecomment_this_time_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="damagelist",
            old_name="damage_max_lank",
            new_name="damage_lank",
        ),
        migrations.RemoveField(
            model_name="damagelist",
            name="damage_min_lank",
        ),
    ]
