# Generated by Django 4.2.7 on 2024-08-01 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0061_rename_damage_max_lank_damagelist_damage_lank_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fullreportdata",
            name="damage_unit",
        ),
    ]
