# Generated by Django 4.2.7 on 2024-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0062_remove_fullreportdata_damage_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="damagecomment",
            options={
                "ordering": [
                    "span_number_order",
                    "parts_order",
                    "parts_name_order",
                    "damage_name_order",
                ]
            },
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="damage_name_order",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="parts_name_order",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="parts_order",
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="damagecomment",
            name="span_number_order",
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
