# Generated by Django 4.2.7 on 2024-08-02 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0063_alter_damagecomment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="damagecomment",
            options={},
        ),
        migrations.RemoveField(
            model_name="damagecomment",
            name="damage_name_order",
        ),
        migrations.RemoveField(
            model_name="damagecomment",
            name="parts_name_order",
        ),
        migrations.RemoveField(
            model_name="damagecomment",
            name="parts_order",
        ),
        migrations.RemoveField(
            model_name="damagecomment",
            name="span_number_order",
        ),
    ]
