# Generated by Django 4.2.7 on 2024-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0066_damagecomment_comment_parts_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagecomment",
            name="auto_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
