# Generated by Django 4.2.7 on 2024-08-06 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0070_customuser_name_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="name",
            new_name="company",
        ),
    ]
