# Generated by Django 4.2.7 on 2024-08-06 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("infra", "0071_rename_name_customuser_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
